
export const currencies = [
  { code: "AED", name: "UAE Dirham", flag: "ae" },
  { code: "AFN", name: "Afghan Afghani", flag: "af" },
  { code: "ALL", name: "Albanian Lek", flag: "al" },
  { code: "AMD", name: "Armenian Dram", flag: "am" },
  { code: "ANG", name: "Netherlands Antillean Guilder", flag: "cw" },
  { code: "AOA", name: "Angolan Kwanza", flag: "ao" },
  { code: "ARS", name: "Argentine Peso", flag: "ar" },
  { code: "AUD", name: "Australian Dollar", flag: "au" },
  { code: "AWG", name: "Aruban Florin", flag: "aw" },
  { code: "AZN", name: "Azerbaijani Manat", flag: "az" },
  { code: "BAM", name: "Bosnia‑Herzegovina Marka", flag: "ba" },
  { code: "BBD", name: "Barbadian Dollar", flag: "bb" },
  { code: "BDT", name: "Bangladeshi Taka", flag: "bd" },
  { code: "BGN", name: "Bulgarian Lev", flag: "bg" },
  { code: "BHD", name: "Bahraini Dinar", flag: "bh" },
  { code: "BIF", name: "Burundian Franc", flag: "bi" },
  { code: "BMD", name: "Bermudian Dollar", flag: "bm" },
  { code: "BND", name: "Brunei Dollar", flag: "bn" },
  { code: "BOB", name: "Bolivian Boliviano", flag: "bo" },
  { code: "BRL", name: "Brazilian Real", flag: "br" },
  { code: "BSD", name: "Bahamian Dollar", flag: "bs" },
  { code: "BTN", name: "Bhutanese Ngultrum", flag: "bt" },
  { code: "BWP", name: "Botswana Pula", flag: "bw" },
  { code: "BYN", name: "Belarusian Ruble", flag: "by" },
  { code: "BZD", name: "Belize Dollar", flag: "bz" },
  { code: "CAD", name: "Canadian Dollar", flag: "ca" },
  { code: "CDF", name: "Congolese Franc", flag: "cd" },
  { code: "CHF", name: "Swiss Franc", flag: "ch" },
  { code: "CLP", name: "Chilean Peso", flag: "cl" },
  { code: "CNY", name: "Chinese Yuan", flag: "cn" },
  { code: "COP", name: "Colombian Peso", flag: "co" },
  { code: "CRC", name: "Costa Rican Colon", flag: "cr" },
  { code: "CUP", name: "Cuban Peso", flag: "cu" },
  { code: "CVE", name: "Cape Verde Escudo", flag: "cv" },
  { code: "CZK", name: "Czech Koruna", flag: "cz" },
  { code: "DJF", name: "Djiboutian Franc", flag: "dj" },
  { code: "DKK", name: "Danish Krone", flag: "dk" },
  { code: "DOP", name: "Dominican Peso", flag: "do" },
  { code: "DZD", name: "Algerian Dinar", flag: "dz" },
  { code: "EGP", name: "Egyptian Pound", flag: "eg" },
  { code: "ERN", name: "Eritrean Nakfa", flag: "er" },
  { code: "ETB", name: "Ethiopian Birr", flag: "et" },
  { code: "EUR", name: "Euro", flag: "eu" },
  { code: "FJD", name: "Fiji Dollar", flag: "fj" },
  { code: "FKP", name: "Falkland Islands Pound", flag: "fk" },
  { code: "GBP", name: "British Pound", flag: "gb" },
  { code: "GEL", name: "Georgian Lari", flag: "ge" },
  { code: "GHS", name: "Ghanaian Cedi", flag: "gh" },
  { code: "GIP", name: "Gibraltar Pound", flag: "gi" },
  { code: "GMD", name: "Gambian Dalasi", flag: "gm" },
  { code: "GNF", name: "Guinean Franc", flag: "gn" },
  { code: "GTQ", name: "Guatemalan Quetzal", flag: "gt" },
  { code: "GYD", name: "Guyanese Dollar", flag: "gy" },
  { code: "HKD", name: "Hong Kong Dollar", flag: "hk" },
  { code: "HNL", name: "Honduran Lempira", flag: "hn" },
  { code: "HRK", name: "Croatian Kuna", flag: "hr" },
  { code: "HTG", name: "Haitian Gourde", flag: "ht" },
  { code: "HUF", name: "Hungarian Forint", flag: "hu" },
  { code: "IDR", name: "Indonesian Rupiah", flag: "id" },
  { code: "ILS", name: "Israeli Shekel", flag: "il" },
  { code: "INR", name: "Indian Rupee", flag: "in" },
  { code: "IQD", name: "Iraqi Dinar", flag: "iq" },
  { code: "IRR", name: "Iranian Rial", flag: "ir" },
  { code: "ISK", name: "Iceland Krona", flag: "is" },
  { code: "JMD", name: "Jamaican Dollar", flag: "jm" },
  { code: "JOD", name: "Jordanian Dinar", flag: "jo" },
  { code: "JPY", name: "Japanese Yen", flag: "jp" },
  { code: "KES", name: "Kenyan Shilling", flag: "ke" },
  { code: "KGS", name: "Kyrgyzstani Som", flag: "kg" },
  { code: "KHR", name: "Cambodian Riel", flag: "kh" },
  { code: "KMF", name: "Comorian Franc", flag: "km" },
  { code: "KRW", name: "South Korean Won", flag: "kr" },
  { code: "KWD", name: "Kuwaiti Dinar", flag: "kw" },
  { code: "KYD", name: "Cayman Islands Dollar", flag: "ky" },
  { code: "KZT", name: "Kazakhstani Tenge", flag: "kz" },
  { code: "LAK", name: "Laotian Kip", flag: "la" },
  { code: "LBP", name: "Lebanese Pound", flag: "lb" },
  { code: "LKR", name: "Sri Lankan Rupee", flag: "lk" },
  { code: "LRD", name: "Liberian Dollar", flag: "lr" },
  { code: "LSL", name: "Lesotho Loti", flag: "ls" },
  { code: "LYD", name: "Libyan Dinar", flag: "ly" },
  { code: "MAD", name: "Moroccan Dirham", flag: "ma" },
  { code: "MDL", name: "Moldovan Leu", flag: "md" },
 { code: "PKR", name: "Pakistani Rupee", flag: "pk" },
 { code: "USD", name: "United States Dollar", flag: "us" }

];
